# Generated by Django 4.0.4 on 2022-11-05 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('text_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='texttraducao',
            name='date_created',
        ),
    ]
