# Generated by Django 4.0.4 on 2022-11-05 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('text_app', '0002_remove_texttraducao_date_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='text',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='textwriting',
            name='date_created',
        ),
    ]
