# Generated by Django 4.0.4 on 2022-11-05 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text_app', '0003_remove_text_date_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='textwriting',
            name='criado_por',
        ),
        migrations.AddField(
            model_name='text',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.DeleteModel(
            name='TextTraducao',
        ),
        migrations.DeleteModel(
            name='TextWriting',
        ),
    ]
