# Generated by Django 4.0.4 on 2022-11-05 21:58

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('text_app', '0004_remove_textwriting_criado_por_text_date_created_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextWriting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, unique=True)),
                ('texto', ckeditor.fields.RichTextField()),
                ('comentario', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Textos-Escritos',
                'ordering': ('titulo',),
            },
        ),
        migrations.CreateModel(
            name='TextTraducao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_traducao', models.CharField(max_length=200, unique=True)),
                ('texto_traducao', ckeditor.fields.RichTextField()),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('text_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='text_app.text')),
            ],
            options={
                'verbose_name_plural': 'Textos-Traduzidos',
                'ordering': ('titulo_traducao',),
            },
        ),
    ]
