# Generated by Django 4.0.4 on 2022-09-07 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('grammar_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grammar_Phrase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frase', models.CharField(max_length=200)),
                ('traducao', models.CharField(max_length=200)),
                ('explicacao', models.CharField(blank=True, max_length=300, null=True)),
                ('grammar_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='grammar_app.grammar')),
            ],
        ),
    ]
