# Generated by Django 4.0.4 on 2022-10-07 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grammar_app', '0004_alter_grammar_id'),
        ('phrases_app', '0002_grammar_phrase_criado_por'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grammar_phrase',
            name='grammar_id',
            field=models.ForeignKey(blank=True, default='teste', null=True, on_delete=django.db.models.deletion.CASCADE, to='grammar_app.grammar'),
        ),
    ]
