# Generated by Django 4.0.4 on 2022-12-01 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phrases_app', '0005_alter_grammar_phrase_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='grammar_phrase',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='grammar_phrase',
            name='frase',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
