# Generated by Django 4.1.4 on 2023-04-25 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phrases_app', '0007_remove_grammar_phrase_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grammar_phrase',
            name='explicacao',
        ),
        migrations.AddField(
            model_name='grammar_phrase',
            name='observacao',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
