# Generated by Django 4.1.4 on 2023-06-02 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grammar_app', '0007_grammar_explicacao'),
        ('phrases_app', '0008_remove_grammar_phrase_explicacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grammar_phrase',
            name='grammar_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grammar_phrases', to='grammar_app.grammar'),
        ),
    ]
