# Generated by Django 4.0.4 on 2022-09-23 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={},
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='criado_por',
        ),
    ]
