# Generated by Django 4.0.4 on 2022-10-21 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0004_profile_delete_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='nome',
        ),
    ]
