# Generated by Django 4.0.4 on 2022-10-22 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0005_remove_profile_nome'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='profile_pic',
            new_name='foto_perfil',
        ),
    ]
