# Generated by Django 4.0.4 on 2022-09-07 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grammar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gramatica', models.CharField(max_length=200)),
                ('estrutura', models.CharField(max_length=200)),
                ('nivel', models.CharField(choices=[('N5', 'N5'), ('N4', 'N4'), ('N3', 'N3'), ('N2', 'N2'), ('N1', 'N1'), ('UNKNOW', 'UNKNOW')], max_length=6)),
            ],
        ),
    ]
