# Generated by Django 4.0.4 on 2022-09-03 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grammar_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grammar_phrase',
            name='explicacao',
            field=models.CharField(default=2, max_length=300),
            preserve_default=False,
        ),
    ]
