# Generated by Django 4.0.4 on 2022-09-04 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grammar_app', '0002_grammar_phrase_explicacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grammar_phrase',
            name='explicacao',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
