# Generated by Django 4.0.4 on 2022-09-29 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grammar_app', '0003_alter_grammar_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grammar',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
