# Generated by Django 4.0.4 on 2022-09-07 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grammar_app', '0003_alter_grammar_phrase_explicacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grammar',
            name='frases',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='grammar_app.grammar_phrase'),
        ),
    ]
