# Generated by Django 4.0.4 on 2022-12-01 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grammar_app', '0004_alter_grammar_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='grammar',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='grammar',
            name='gramatica',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
