# Generated by Django 4.0.4 on 2022-11-27 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary_app', '0002_alter_category_options_alter_word_antonimo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conjugation',
            name='palavra',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vocabulary_app.word'),
        ),
    ]
