# Generated by Django 4.0.4 on 2022-11-28 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary_app', '0003_alter_conjugation_palavra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='nome',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='word',
            name='antonimo',
            field=models.CharField(blank=True, default='---', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='word',
            name='traducao',
            field=models.CharField(max_length=200),
        ),
    ]
