# Generated by Django 4.0.4 on 2022-11-28 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='example',
            options={'ordering': ('frase',), 'verbose_name_plural': 'Exemplos'},
        ),
        migrations.AlterField(
            model_name='example',
            name='leitura',
            field=models.CharField(max_length=200),
        ),
    ]
