# Generated by Django 4.0.4 on 2022-11-28 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example_app', '0002_alter_example_options_alter_example_leitura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='example',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
